require('./dino-test')
require('./cactus-test')
require('./block-test')
require('./create-point-test')
require('./points-equal-test')
require('./blocks-overlap-test')
require('./collision-test')
require('./score-test')
